terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
timeout: la commande surveillée a renvoyé un core dump
